before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --default-toolchain=nightly -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - rustup target add wasm32-unknown-unknown
  - cargo +nightly install wasm-bindgen-cli --version 0.2.28

language: node_js
node_js:
  - "10.5"
cache:
  - yarn
  - cargo

notifications:
  email: false
