[package]
name = "editor-backend"
version = "0.1.0"
authors = ["marcusdarmstrong <marcusdarmstrong@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.14"

[profile.release]
lto = true